### ISSUE TITLE
海戦ゲーム

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/Battleship#1]
- マスに隠れた戦艦を探して全て倒すゲーム
- マスは8x8
- 戦艦は長さ3、4、5が一隻ずつ
- マスを選べる回数は24回

**Comment by konta3291** [comment]
お世話になっております。
海戦ゲームの仕様について確認したいことがございます。
確認したいことは下記の通りです。
 - ゲーム起動後の開始文言はどういたしましょうか。
 - 攻撃するマスの入力を求める文言はどういたしましょうか。
 - 攻撃するマスの入力を求める際、受け付ける入力はどういたしましょうか。
 - 攻撃したマスが戦艦マスの周りに触れていた場合の挙動はどういたしましょうか。
 - 攻撃したマスが戦艦マスに命中した場合の挙動はどういたしましょうか。
 - 攻撃したマスがただのマスの場合の挙動はどういたしましょうか。
 - クリア後の挙動はどういたしましょうか。
 - 24回以内にクリアできなかった場合の挙動はどういたしましょうか。
 - 表示する表はどういたしましょうか。
 例）
  　　a　b　c　d　e　f　g　h
      1
      2
      3
      4
      5
      6
      7
      8 

以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
1. `【BATTLESHIP】`と表示してください。
2. 文言は不要です。
3. 十字キーでカーソル移動、EnterまたはSpaceで攻撃です。
4. 何もしません。
5. 選んでいたマスに`○`を書き加えてください。
6. 選んでいたマスに`×`を書き加えてください。
7. リトライするか聞いてください。
8. ゲームオーバーの旨を表示し、リトライするか聞いてください。
9. 列は小文字ではなく大文字でお願いします。
列の区切りは半角スペースで、1マスは半角2文字（全角1文字）です。
列のローマ字の上に現在選択している列を`↓`で明示、
同じく行の数字の左に現在選択している行を`→`で明示するようお願いします。

なんか項目が多いと入力しててどれがどれだかわからなくなったので
中点段落じゃなくて数字段落で書くようお願いします。

**Comment by konta3291** [comment]
見づらい書き方をしてしまい申し訳ありません。数字で書くようにします。

ご回答ありがとうございます。
追加で確認したいことがございます。
確認したい内容は下記の通りです。
 1. リトライの文言はどういたしましょうか。
 2. リトライ時に受け付ける入力はどういたしましょうか。
 3. リトライ時に受け付けていない入力があった場合の挙動はどういたしましょうか。
 4. リトライ後も【BATTLESHIP】と表示するようにしますか。


以上です。ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
1. `リトライしますか？(Y/N)`でお願いします。
2. YかNです。
3. 無視します。
4. タイトルは表示しっぱなしでお願いします。

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、では確認した仕様で作業を進めます。
ありがとうございました。

**Comment by konta3291** [comment]
お世話になっております。
海戦ゲームの仕様についてご確認したいことがございます。
ご確認したいことは下記の通りです。
 1. 1マス半角2文字とのことですが、カーソルの移動は半角1文字移動、半角2文字移動どちらにいたしましょうか。
 2. 既に攻撃済みのマスにもう一度攻撃した場合の挙動はどういたしましょうか。24回の選択から一回分減らしますか。
 3. 攻撃したマスに表示する〇×は全角、半角どちらにいたしましょうか。
 4. リプレイを聞く画面では、ゲームテーブルの表示はどういたしましょうか。
 5. リプレイ文言の表示位置はどういたしましょうか。
 6. ゲームテーブルのデザインはどういたしましょうか。例）外枠線あり、格子線なし  or  外枠線あり、格子線あり
 7. 外枠線からカーソルが出ないようにするカーソル移動制限はどういたしましょうか。
 8. 毎ゲームごとの戦艦の位置はどういたしましょうか。
 9. 戦艦の形はどういたしましょうか。


以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
1. 1回の左右移動で1マス移動させたいです。
2. 弾は撃たない（攻撃操作を受け付けない）です。
3. 全角です。全角文字しかないので。
4. リプレイするかを決定するまではそのままです。
5. マップの下にお願いします。
6. 外枠あり、内枠（格子）無しです。
7. 端を選択中に外に向かってカーソル操作しても移動しないようお願いします。
8. ランダムです。
9. 全て｜または−の形です。斜めはありません。

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、では確認した仕様で作業を進めます。
ありがとうございました。

**Comment by konta3291** [comment]
お世話になっております。
海戦ゲームの仕様についてご確認したいことがございます。
ご確認したいことは下記の通りです。
 - リトライ時にy,n小文字で入力された場合の挙動はどういたしましょうか。


以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
小文字でもOKです。

開発者曰く、カーソル移動と攻撃確定と同じようなキー入力処理でいいんじゃね？

**Comment by konta3291** [comment]
ご回答ありがとうございます。
仕様の変更をするうえで、下記のご確認したいことがございます。
 1. 文字の入力は受け付けないで、あらかじめ表示されているY,Nをカーソルであて、EnterやSpaceで決定するといことでしょうか。
 2. その場合、リプレイ文言の変更はどういたしましょうか。

お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
それはここで聞くことじゃないけど、
「Y」キーと「N」キーを識別するようにするってこと。文言は提示内容そのままでいいんじゃないかな。

**Comment by konta3291** [comment]
ここで仕様以外の質問をしてしまい申し訳ありません。

ご回答ありがとうございます。
かしこまりました、では確認した仕様で作業を進めます。
ありがとうございました。
