### ISSUE TITLE
残弾表示機能

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/Battleship#10]
残弾数を表示したい。

**Comment by konta3291** [comment]
お世話になっております。
残弾表示機能追加の仕様について確認したいことがございます。
確認したいことは下記の通りです。
 1. 表示する位置はどういたしましょうか。
 2. 表示する文言はどういたしましょうか。


以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
1. マスのすぐ下がいいです
2. `残弾：◯◯◯◯◯◯◯×××`のような形がいいです

**Comment by konta3291** [comment]
ご回答ありがとうございます。
追加で確認したいことがございます。
確認したい内容は下記の通りです。
 - ゲーム終了後にゲームテーブルのすぐ下に終了、リプレイメッセージを表示しているのですが、
 残弾の表示をテーブルのすぐ下に表示しますと、終了とリプレイメッセージの表示位置はどういたしましょうか。

以上です。ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
終了メッセージ類は一番下でお願いします

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、では確認した仕様で作業を進めます。
ありがとうございました。
