### ISSUE TITLE
カーソルのサイズが違う

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/Battleship#11]
未攻撃のマスと攻撃済のマスでカーソルのサイズが異なっている。

**Comment by konta3291** [comment]
バグを発生させてしまい大変申し訳ございません。
バグの修正にあたって確認したいことがございます。
確認したいことは下記の通りです。
 - カーソルのサイズは半角カーソル、全角カーソルどちらにいたしましょうか。


以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
ゲーム全体で全角基準で指示してあるはずなので全角です

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、では確認した仕様で作業を進めます。
ありがとうございました。
