### ISSUE TITLE
リトライを確認するメッセージが不自然

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/Battleship#19]
- 余計な`:`が混入している。
- コマンドプロンプトの続行を確認するメッセージが同じ行に表示される。

**Comment by konta3291** [comment]
お世話になっております。
リトライを確認する不自然なメッセージの改善について確認したいことがございます。
確認したいことは下記の通りです。
 - 修正後表示するリトライメッセージはこちらでよろしいでしょうか。
 
> リトライしますか？(Y/N)
 _

( _ )は入力待ちのカーソルです。

以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
メッセージに`:`がなくてコマンドプロンプトの続行を確認するメッセージが同じ行に表示されなければいいです。

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、ご確認させていただいた仕様で作業を進めます。
ありがとうございました。

**Comment by konta3291** [comment]
コマンドプロンプトの続行を確認するメッセージの位置を変更しました。
リトライメッセージのすぐ下に表示されるのと、１行空けて表示するのでしたらどちらがお好みでしょうか。

すぐ下に表示：
![スクリーンショット (18)](https://user-images.githubusercontent.com/103171031/196826528-8d3e567d-aa92-4d71-9bae-469994fd0563.png)


１行空けて表示：
![スクリーンショット (19)](https://user-images.githubusercontent.com/103171031/196826558-ad0702ca-c091-4c39-8a1d-62cf15d634d7.png)

ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
後者がいいですね

**Comment by konta3291** [comment]
ご回答いただきありがとうございます。

ではこちらの仕様で作業を進めます。
ありがとうございました。
