### ISSUE TITLE
自動テストしたい

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/Battleship#2]
`HitAndBlow`にあった[dotnet4.yml](https://github.com/konta3291/HitAndBlow/blob/master/.github/workflows/dotnet4.yml)をこっちでも同階層に配置すれば多分動くはず。
最後の行の`run: Fw\External-Bin\Net\2.0\nunit-console.exe HitAndBlowTest\bin\Debug\HitAndBlowTest.dll`の
テストプロジェクト名をBattleship用に書き換える必要はあるけど。

**Comment by konta3291** [comment]
かしこまりました、追加します。
