### ISSUE TITLE
残弾表示が1行に押し込まれている

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/Battleship#20]
十何発分かごとに折り返したい

**Comment by konta3291** [comment]
お世話になっております。
残弾数表示の改善について確認したいことがございます。
確認したいことは下記の通りです。
 1. 弾数によって折り返すようにしますか。例）弾数 : 18なら6毎に、 弾数 : 24なら8毎に
                                               OR
 2. 弾数関係なく、決めた数字に達したら折り返すようにしますか。例）弾数関係なく12毎に折り返す
 
 
以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
なるべく見栄え良い表示がいいです。弾数が少ないのに改行しすぎると見栄え悪くなりますので。

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、見栄えの良い表示になるように修正いたします。
ありがとうございました。

**Comment by konta3291** [comment]
残弾数を11発毎に折り返して表示するように修正いたしました。
こちらはいかがでしょうか。

難易度EASY　弾数18：
![スクリーンショット (15)](https://user-images.githubusercontent.com/103171031/196598436-4ff20da3-9f39-4160-8ce0-5c548c315733.png)

難易度NORMAL　弾数24：
![スクリーンショット (16)](https://user-images.githubusercontent.com/103171031/196598473-f0e45e5b-413c-46c0-ab57-1c2658fea546.png)

難易度HARD　弾数30：
![スクリーンショット (17)](https://user-images.githubusercontent.com/103171031/196598493-6de14542-de48-459e-aada-caa6b4ea0f40.png)

**Comment by Takatatsu9** [comment]
各難易度で、残弾の各行の右端が揃ってるといいですね

**Comment by konta3291** [comment]
残弾が右端揃いになるようにしました。
ご確認の上ご意見よろしくお願いいたします。

難易度EASY　弾数18：
![スクリーンショット (20)](https://user-images.githubusercontent.com/103171031/196867743-6d71e8b2-4934-4fc7-956c-305b523337b4.png)

難易度NORMAL　弾数24：
![スクリーンショット (21)](https://user-images.githubusercontent.com/103171031/196867766-0ece7095-95db-478c-9676-c7ccf6c600c5.png)

難易度HARD　弾数30：
![スクリーンショット (22)](https://user-images.githubusercontent.com/103171031/196867802-fe635e2e-53eb-4680-b371-a5940ddf2e42.png)


ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
NORMAL、HARDで横に長すぎるので3行がいいですね

**Comment by konta3291** [comment]
ご回答ありがとうございます。

かしこまりました、横に長すぎるため3行使って表示するように変更いたします。

**Comment by konta3291** [comment]
弾数表示が横に長くなっていたNORMALとHARDを３行使って表示されるように修正いたしました。

ご確認の上ご意見がありましたらよろしくお願いいたします。

難易度EASY　弾数18：
![スクリーンショット (24)](https://user-images.githubusercontent.com/103171031/197128877-0202d1a6-0624-499d-84b5-c5e8d15cf9e2.png)


難易度NORMAL　弾数24：
![スクリーンショット (25)](https://user-images.githubusercontent.com/103171031/197128914-93b4f54a-6e4a-4648-b3a8-b74483a4606c.png)


難易度HARD　弾数30：
![スクリーンショット (26)](https://user-images.githubusercontent.com/103171031/197128951-b00e9ccf-3bfc-4a46-84e8-db3bee9e1b05.png)

**Comment by Takatatsu9** [comment]
良いですね。
ちょっとご相談なんですが、これ、マスの下ではなく右に表示することってできますか？
右に持っていく場合はEASYでも3列にしてほしいです。

**Comment by konta3291** [comment]
承知致しました。

残弾数の開始位置はどういたしましょうか。
テーブルの右上を表示開始位置にすると下記のようになると思います。
いかがでしょうか。
また、残弾数が表示されていた位置にメッセージを表示してよろしいでしょうか。
ご回答よろしくお願いいたします。

【BATTLESHIP】
 　    ↓
　   ＡＢＣＤＥＦＧＨ
　   ＿＿＿＿＿＿＿＿
→ 1|　　　　　　　　|　残弾：◯◯◯◯◯◯◯◯
　 2|　　　　　　　　|　  　 　   ◯◯◯◯◯◯◯◯
　 3|　　　　　　　　|　  　 　   ◯◯◯◯◯◯◯◯
　 4|　　　　　　　　|
　 5|　　　　　　　　|
　 6|　　　　　　　　|
　 7|　　　　　　　　|
　 8|　　　　　　　　|
　   ￣￣￣￣￣￣￣￣
始まりました！健闘を祈ります！

**Comment by nabemasamasa** [comment]
行は横のライン(上図の1,2,3,,)、列は縦のライン(上図のA,B,C,,,)……。今回要望は「右に持っていく場合はEASYでも3列にしてほしいです。」……。

**Comment by Takatatsu9** [comment]
右に持って行った場合の表示は横並びじゃなくて縦並びです。
こういうことです。
![image](https://user-images.githubusercontent.com/50448373/197138031-656bb8a8-665c-4c7b-b173-052c7c2bfe77.png)

**Comment by konta3291** [comment]
行と列を間違えてしまい申し訳ございません。

かしこまりました、テーブルの右に残弾が3列で表示されるように修正いたします。

**Comment by konta3291** [comment]
> 行は横のライン(上図の1,2,3,,)、列は縦のライン(上図のA,B,C,,,)……。今回要望は「右に持っていく場合はEASYでも3列にしてほしいです。」……。

@nabemasamasa さん
教えてくださりありがとうございます。

**Comment by konta3291** [comment]
弾数をテーブルの右側に３列で表示するように修正いたしました。
ご確認の上ご意見がありましたらよろしくお願いいたします。


難易度EASY　弾数18：
![スクリーンショット (27)](https://user-images.githubusercontent.com/103171031/197424835-3a280052-e8be-428e-b447-a63466611062.png)




難易度NORMAL　弾数24：
![スクリーンショット (28)](https://user-images.githubusercontent.com/103171031/197424842-f9a1989f-9035-43d4-b191-d9adfe398062.png)




難易度HARD　弾数30：
![スクリーンショット (29)](https://user-images.githubusercontent.com/103171031/197424848-3758a818-4e48-4977-912a-9f5b62f0366e.png)

**Comment by Takatatsu9** [comment]
マスと残弾表示の間に隙間が欲しいです。
`残弾`の隣の`：`は不要です。
`残弾`は残弾数の真ん中にくるようにしたいです。
`残弾`は列インデックスの行と同じ位置がいいです。

**Comment by konta3291** [comment]
頂いたご意見をもとに修正いたしました。
マスと残弾表示の間の隙間はもう少し短い方がよろしいでしょうか。
ご確認の上ご意見よろしくお願いいたします。

難易度EASY　弾数18：
![スクリーンショット (30)](https://user-images.githubusercontent.com/103171031/197437920-4544f164-5d80-48ba-8003-742f77aa033d.png)


難易度NORMAL　弾数24：
![スクリーンショット (31)](https://user-images.githubusercontent.com/103171031/197437929-944dc8ac-034d-4c0e-ad47-8c4016a499ef.png)


難易度HARD　弾数30：
![スクリーンショット (32)](https://user-images.githubusercontent.com/103171031/197437939-f2aab8fe-1842-4360-b9cb-3709618cec14.png)

**Comment by Takatatsu9** [comment]
残弾は右下から上に減っていくのがいいです。残弾7/15ならこんな感じ。
```
◯◯×
◯◯×
◯××
◯××
◯××
```

**Comment by konta3291** [comment]
かしこまりました。
右下から上に減っていくように修正いたします。
