### ISSUE TITLE
メッセージが事務的

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/Battleship#21]
- #6 で指示した範囲のメッセージが事務的すぎる
- 軍隊あるいは海賊を彷彿とさせるような荒々しいセリフがいい
- それ以外のメッセージは今のままでいい

**Comment by konta3291** [comment]
かしこまりました。修正いたします。

**Comment by konta3291** [comment]
こちらのメッセージを考えたのですがいかがでしょうか。
 - 開始：  敵はもう周辺にいる！気を引き締めよう！
 
 - 命中：  命中！その調子！
 
 - 1カーソル移動以内：  おしい！すぐそばに敵はいる！

 - 2カーソル移動以内：  敵船は近くにいる！

 - 敵船が近くにいないとき：  敵船は近くにはいない

 - 勝利：  我々の勝利だ！

 - 敗北：  逃してしまった（敗北）
 
 もう少し荒々しい方がよろしいでしょうか。
 ご確認の上ご意見よろしくお願いいたします。

**Comment by Takatatsu9** [comment]
- 開始は「戦闘開始だ！～」のような言葉がいいと思います
- 命中は褒めてあげるのがいいですね、見事だとか上手いぞとか。（勝利時もそんなのがいいかな？）
- 近くにいないときは「そのあたりには～」と文頭に添えるのがいいかなと。
- 敗北は、もっと悔しさが滲み出てる文だといいですね。

**Comment by konta3291** [comment]
ご回答ありがとうございます。
こちらのメッセージはいかがでしょうか。

 - 開始： 戦闘開始だ！全敵船を撃破せよ！

 - 命中： 命中！見事だ！

 - 1カーソル移動以内： おしい！すぐそばに敵はいる！

 - 2カーソル移動以内： 敵船は近くにいる！

 - 敵船が近くにいないとき： この辺りには敵船はいない

 - 勝利： 我々の勝利だ！よくやった！

 - 敗北： 我々の敗北だ、弾数がもう少しあれば、、、
 
 ご確認の上ご意見よろしくお願いいたします。

**Comment by Takatatsu9** [comment]
- 開始は「撃破」よりいい言葉がありそうな気がします。陸上兵器ではなく海上兵器なので。
- 近くにいないときは「その辺り」のほうがいいですね。砲撃は遠距離攻撃になりますので。
あと「いないようだ」と、おそらくそうだろう的な言葉がいいと思います。
ハッキリ居場所がわかるならそこ教えてよって思っちゃうので。
- 敗北で弾数について言及するのはやめましょう、軍資金不足みたいで悲しい・・・

**Comment by konta3291** [comment]
ご意見してくださりありがとうございます。
かしこまりました、いただいたご意見をもとにメッセージを考え直します。

**Comment by konta3291** [comment]
頂いたご意見をもとにメッセージを考えました。
こちらのメッセージはいかがでしょうか。

 - 開始： 戦闘開始だ！全敵船を撃沈せよ！

 - 命中： 命中！見事だ！

 - 1カーソル移動以内： おしい！すぐそばに敵はいる！

 - 2カーソル移動以内： 敵船は近くにいる！

 - 敵船が近くにいないとき： その辺りには敵船はいないようだ

 - 勝利： 我々の勝利だ！よくやった！

 - 敗北： 我々の敗北だ、次は逃さない！

ご確認の上ご意見よろしくお願いいたします。

**Comment by Takatatsu9** [comment]
いいと思います！あと一点だけ、「敵船」を「敵艦」表記にしてください。それでOKです。

**Comment by konta3291** [comment]
ご回答ありがとうございます。
承知致しました。では下記のメッセージが表示されるように変更いたします。
ご相談に乗って頂きありがとうございました。

 - 開始： 戦闘開始だ！全敵艦を撃沈せよ！

 - 命中： 命中！見事だ！

 - 1カーソル移動以内： おしい！すぐそばに敵はいる！

 - 2カーソル移動以内： 敵艦は近くにいる！

 - 敵艦が近くにいないとき： その辺りには敵艦はいないようだ

 - 勝利： 我々の勝利だ！よくやった！

 - 敗北： 我々の敗北だ、次は逃さない！
