### ISSUE TITLE
メッセージ表示

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/Battleship#6]
プレイヤーの行動に対してメッセージを表示したい
1. ゲーム開始時に、健闘を祈る的な文章
1. 攻撃が当たったら、命中した旨の文章
1. 攻撃が当たらず、±1マス以内に敵がいたら、攻撃が外れた旨の文章
1. 攻撃が当たらず、±2マス以内に敵がいたら、付近に敵がいる旨の文章
1. 攻撃が当たらず、`3.`、`4.`に当てはまらなければ、付近に敵がいない旨の文章
1. 勝利したら褒める文章
1. 敗北したら慰める文章

**Comment by Takatatsu9** [comment]
少し追加しました

**Comment by konta3291** [comment]
お世話になっております。
メッセージ表示機能追加の仕様について確認したいことがございます。
確認したいことは下記の通りです。
 1. メッセージを表示する位置はどういたしましょうか。
 2. ゲーム開始時の健闘を祈る文言はいつまで表示しましょうか。例）カーソル移動するまで。　初攻撃があるまで。
 3. 各文言は私の方で決めてよろしいでしょうか。


以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
1. 残弾数の下にお願いします
2. 攻撃のタイミングで更新してください
3. はい。お願いします

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、では確認した仕様で作業を進めます。
ありがとうございました。

**Comment by konta3291** [comment]
メッセージ表示機能追加の仕様について追加で確認したいことがございます。

 - 「±2マス以内に敵がいたら」についてですが、範囲の認識は下記の通りでよろしいでしょうか。

「〇」はメッセージ表示対象位置です

〇✕〇✕〇✕
✕〇〇〇✕✕
〇〇敵〇〇
✕〇〇〇✕✕
〇✕〇✕〇✕


以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
✕✕✕✕✕✕✕
✕✕✕〇✕✕✕
✕✕〇〇〇✕✕
✕〇〇敵〇〇✕
✕✕〇〇〇✕✕
✕✕✕〇✕✕✕
✕✕✕✕✕✕✕
です。カーソル移動2回以内の範囲という認識です。

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、ご確認させていただいた仕様で作業を進めます。
ありがとうございました。

**Comment by konta3291** [comment]
メッセージ表示機能追加の仕様について追加で確認したいことがございます。
ご確認したい内容は下記の通りです。
 1. 攻撃したマスの近く(1or2マス以内)に攻撃済みの敵船があった場合はどういたしましょうか。攻撃済みのため、敵船として認識しないでよろしいでしょうか。
 2. 攻撃が敵船に当たらず、1マスと2マス近くに敵船があった場合の文言はどういたしましょうか。　例）1マス以内の文言のみ表示　or 1マスと2マスどちらの文言も表示
 3. 勝利したら褒める文章、敗北したら慰める文章の表示ですが、ゲームオーバー文言とクリア文言とは別のものでしょうか。

例）
　　　テーブル　　　　　　　　　　　　　　　　　　　　　　　　テーブル
ー－－－－－－－－－－－　　　　　　OR　　　　　　　　　　ー－－－－－－－－－
残弾表示　　　　　　　　　　　　　　　　　　　　　　　　　　残弾表示
褒めるメッセージ　　　　　　　　　　　　　　　　　　　　　　褒めるメッセージ
クリアメッセージ　　　　　　　　　　　　　　　　　　　　　　リプレイ文言
リプレイ文言


以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by konta3291** [comment]
メッセージ表示機能追加の仕様について追加で確認したいことがございます。
ご確認したい内容は下記の通りです。
 - 攻撃済みのマスを攻撃しようとしても残弾は減らないのですが、メッセージは更新はどういたしましょうか。


以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
1. 撃墜済のマスは無いものとして扱ってください
2. 一番近いものを優先してください
3. 別です
4. しません

**Comment by konta3291** [comment]
ご回答ありがとうございます。
ゲームクリア後に表示するメッセージは下記の通りでよろしいでしょうか。

　　　テーブル　　　　　　
ー－－－－－－－－－－－　
残弾表示　　　　　　　　　
褒めるメッセージ　　　　　
クリアメッセージ　　　　　
リプレイ文言

お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
クリアメッセージってリプレイメッセージのことかと思いました。
```
マス
残弾
メッセージ
リプレイ
```
です。

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、ご確認させていただいた仕様で作業を進めます。
ありがとうございました。
