### ISSUE TITLE
ゲームオーバー時の回答表示

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/Battleship#7]
ゲームオーバー時、敵船の位置に`△`を表示する

**Comment by konta3291** [comment]
お世話になっております。
ゲームオーバー時に解答を表示する機能追加の仕様について確認したいことがございます。
確認したいことは下記の通りです。
 - ゲームオーバー時、敵船を攻撃済みのマスの表示はどういたしましょうか。　例）△で表示。　〇のまま表示


以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
そのまま表示してください。

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、では確認した仕様で作業を進めます。
ありがとうございました。
