### ISSUE TITLE
難易度変更機能

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/Battleship#8]
難易度を選択できるようにしたい。

- EASY
    - 6x6マス
    - 弾数18
    - 敵船は4、3
- NORMAL
    - 現在の仕様のまま
- HARD
    - 10x10マス
    - 弾数30
    - 敵船は5、4、3、2

**Comment by konta3291** [comment]
お世話になっております。
難易度変更機能追加の仕様について確認したいことがございます。
確認したいことは下記の通りです。
 1. 難易度を聞くタイミングはどういたしましょうか。
 2. 難易度を聞く文言はどういたしましょうか。
 3. 難易度で受け付ける入力はどういたしましょうか。


以上です。お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
1. ゲーム開始です
2. 「難易度を選択してください」です
3. カーソルで選んで決定で確定です

**Comment by konta3291** [comment]
ご回答ありがとうございます。
追加でご確認したいことがございます。ご確認したいことは下記の通りです。
 1. ゲーム開始時にタイトルやゲームテーブルを表示しているのですが、難易度変更機能を追加後、開始時に表示されるものはどういたしましょうか。
 2. カーソルで選択するものは、どういたしましょうか。
 3. 決定キーはどういたしましょうか。例）Entreのみ、EntreとSpace


お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
1. 難易度選択メッセージのみです
2. カーソルで選択するものは難易度です
3. 後者でお願いします

**Comment by konta3291** [comment]
ご回答ありがとうございます。
では、開始時に画面に表示されているものは下記ものでよろしいでしょうか。

**難易度を選択してください
EASY　NORMAL　HARD**

お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
はい。選択中の難易度は【】で囲ってください

**Comment by konta3291** [comment]
ご回答ありがとうございます。
 - 選択中の難易度を【】で囲むのですが、カーソルの表示はどういたしましょうか。

お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
【】がカーソルです

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、ご確認させていただいた仕様で作業を進めます。
ありがとうございました。

**Comment by konta3291** [comment]
仕様について追加でご確認したいことと、相談したいことがございます。
ご確認したいことは下記の通りです。
 - リプレイ後、もう一度難易度選択を求めますか。
 

相談したいことは下記の通りです。
列を表すローマ字が今半角になっているのですが、現在列位置を表す矢印が全角のためローマ字ではなく、ローマ字の右端を指しているように見える状態になっております。
 - 矢印とのズレがないようにローマ字の全角表示どういたしましょうか。

お忙しいところ恐れ入りますが、ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
1. はい、表示してください
2. 今の状態とその場合の比較が見たいです

**Comment by konta3291** [comment]
ご回答ありがとうございます。

ローマ字半角の場合：
![スクリーンショット (13)](https://user-images.githubusercontent.com/103171031/190027890-2a9eccea-f6cd-4e92-8220-668e78b2700f.png)


ローマ字全角の場合：
![スクリーンショット (12)](https://user-images.githubusercontent.com/103171031/190027930-778d24fb-7067-4c1c-a082-77474f6e3f2d.png)

ご回答よろしくお願いします。

**Comment by Takatatsu9** [comment]
では全角でお願いします

**Comment by konta3291** [comment]
ご回答ありがとうございます。
かしこまりました、ご確認させていただいた仕様で作業を進めます。
ありがとうございました。
