### ISSUE TITLE
操作時の画面点滅をなくしたい

### ISSUE THREAD

**Issue by Takatatsu9** [konta3291/Battleship#9]
操作時に画面が点滅するのをなくしたい。

**Comment by Takatatsu9** [comment]
（開発者としてのアドバイス）
コンソールは画面全体クリア以外にも、コードでカーソルを動かして書き換えというのができるらしい。
変更のあった箇所だけを書き換えれば点滅を防げるのでは？

実は世の中にあるゲームも、愚直にクリア→描画するとこういう点滅が起きる。
それを防ぐために、裏画面というものを用意し、まずはそこにグラフィックを描き込んでから
人がいつも見てる表画面に（表画面をクリアせず）裏画面を転写することで点滅を防いでる。

**Comment by konta3291** [comment]
> （開発者としてのアドバイス） コンソールは画面全体クリア以外にも、コードでカーソルを動かして書き換えというのができるらしい。 変更のあった箇所だけを書き換えれば点滅を防げるのでは？
> 
> 実は世の中にあるゲームも、愚直にクリア→描画するとこういう点滅が起きる。 それを防ぐために、裏画面というものを用意し、まずはそこにグラフィックを描き込んでから 人がいつも見てる表画面に（表画面をクリアせず）裏画面を転写することで点滅を防いでる。

貴重なアドバイスありがとうございます。
裏画面について調べ、こちらの改善を進めていきます。

**Comment by Takatatsu9** [comment]
裏画面について調べてもコンソール画面に関する情報は一切出てこないと思います。
そもそも動きが違うので。

**Comment by konta3291** [comment]
自分で調べ、
わからなかった場合は大変申し訳ないのですが、何と調べれば良いのかお聞きしてよろしいでしょうか。

**Comment by Takatatsu9** [comment]
> コンソールは画面全体クリア以外にも、コードでカーソルを動かして書き換えというのができるらしい。
変更のあった箇所だけを書き換えれば点滅を防げるのでは？

これだけじゃ何言ってるかわからない、ということでよろしいですか？
（はい/いいえ以外の回答は全て「いいえ」と捉えます）

**Comment by konta3291** [comment]
いいえ

読み直しましたら、理解できました。
ありがとうございます。
